name: Tell www.dispatch.forum to deploy preview

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "$GITHUB_REF_NAME"
        id: extract_branch
      - name: Send a workflow dispatch to re-deploy staging with the latest code
        run: |
          curl \
            -X POST \
            -H 'Accept: application/vnd.github+json' \
            -H 'Authorization: token ${{ secrets.WEBSITE_STAGING_REDEPLOY_TOKEN }}' \
            'https://api.github.com/repos/usedispatch/www.dispatch.forum/actions/workflows/deploy_preview.yml/dispatches' \
            -d '{"ref":"main","inputs":{ "branch": "$GITHUB_REF_NAME" }}'
