name: Tell www.dispatch.forum to deploy staging

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Send a workflow dispatch to re-deploy staging with the latest code
        run: curl \
          -X POST \
        -H 'Accept: application/vnd.github+json' \
        -H 'Authorization: token ${{ secrets.VERCEL_TOKEN }}' \
        'https://api.github.com/repos/usedispatch/www.dispatch.forum/actions/workflows/deploy_staging.yml/dispatches' \
        -d '{"ref":"main","inputs":{}}'
