name: Tell www.dispatch.forum to deploy staging

on:
  push:
    branches-ignore:
      - master
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Send a workflow dispatch to re-deploy staging with the latest code
        run: |
          curl \
            -X POST \
            -H 'Accept: application/vnd.github+json' \
            -H 'Authorization: token ${{ secrets.WEBSITE_STAGING_REDEPLOY_TOKEN }}' \
            'https://api.github.com/repos/usedispatch/www.dispatch.forum/actions/workflows/deploy_preview.yml/dispatches' \
            -d '{"ref":"main","inputs":{ branch: ${{steps.extract_branch.outputs.branch}} }}'
